### ISSUE TITLE
How to use RT-DETR model?

### ISSUE THREAD

**Issue by Subhankhan41** [sovit-123/vision_transformers#23]
Hi Sovit,

Sorry to bother you again, I have trained the model using DETR and it worked really well thanks to you. However, I see you do have RT-DETR model too in the detection folder, but I can't seem to find on how you are using it in your model list. In fact, I don't see them in the available model list you mentioned at the start. Could you please guide me how can I use RT-DETR to train the model?

Thanks

**Comment by sovit-123** [comment]
Hi. Right now, RT-DETR is only available for inference. I have not updated README docs with the inference steps. However, you can find it here in the article => https://debuggercafe.com/rt-detr/

I will update the docs soon.

**Comment by Subhankhan41** [comment]
Thanks for letting me know.

**Comment by sovit-123** [comment]
Welcome.
