### ISSUE TITLE
RT-DETRV2 compatibility

### ISSUE THREAD

**Issue by nicklasb** [sovit-123/vision_transformers#24]
Hi, 

Thanks for a nice library, well needed!
So I trained a model with RT-DETRV2 and tried inferring using inference_image_detect.py, but ran into some trouble.

Am I right in assuming that this library doesn't support v2 yet?
Because I got this error (after running with a config to get that for), which seems to assume a structure that is not there?

File "C:\Users\Nickl\Projects\vision_transformers\tools\utils\detection\detr\general.py", line 252, in load_weights
    model = DETRModel(num_classes=NUM_CLASSES, model=ckpt['model_name'])
    
Kind regards, Nicklas

**Comment by sovit-123** [comment]
Hello @nicklasb 
It is great that you were able to train the RT-DETRV2 model. Unfortunately, the library supports fine-tuning for DETR and inference for RT-DETR (not v2) at the moment. I am planning to add more functionalities soon.

**Comment by nicklasb** [comment]
Understood. I managed to get things to work without it, so I am ok with that.
